name: Generate OGP Image

on:
  workflow_dispatch:
    inputs:
      title:
        description: '画像に入れるタイトル'
        required: true
        default: 'デフォルトタイトル'
      bgColor:
        description: '背景色（例: #ffffff）'
        required: false
        default: '#f8f8f8'
      type:
        description: '出力種別'
        required: true
        type: choice
        options:
          - LP
          - 比較表
          - SNS告知

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: 入力内容の確認
        run: |
          echo "タイトル: ${{ github.event.inputs.title }}"
          echo "背景色: ${{ github.event.inputs.bgColor }}"
          echo "種別: ${{ github.event.inputs.type }}"
