name: Export PR Notes to Notion

on:
  pull_request:
    types:
      - closed

jobs:
  export-notes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract PR Body & Send to Notion
        uses: actions/github-script@v7
        with:
          script: |
            const axios = require('axios');

            const prBody = github.event.pull_request.body;

            const match = prBody.match(/## 仕様外で実装した工夫・判断[\s\S]*?(?=(## |$))/);
            const notes = match ? match[0].replace(/^## .*\n/, '').trim() : '';

            if (!notes) {
              console.log('No custom notes found. Skipping.');
              return;
            }

            const notionPayload = {
              parent: { database_id: process.env.NOTION_DATABASE_ID },
              properties: {
                Name: { title: [{ text: { content: github.event.pull_request.title } }] },
                PR: { url: github.event.pull_request.html_url }
              },
              children: [
                {
                  object: 'block',
                  type: 'paragraph',
                  paragraph: {
                    text: [{ type: 'text', text: { content: notes } }]
                  }
                }
              ]
            };

            await axios.post('https://api.notion.com/v1/pages', notionPayload, {
              headers: {
                'Authorization': `Bearer ${process.env.NOTION_TOKEN}`,
                'Notion-Version': '2022-06-28',
                'Content-Type': 'application/json'
              }
            });

          result-encoding: string
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
